<script>
	users=[];
    class Person{
	constructor(firstname,lastname, mobilenumber){
     this.firstname= firstname;
     this.lastname= lastname;
     this.mobilenumber=mobilenumber;
     }
     fullName(firstname,lastname){
     return `${firstname}  ${lastname}`;
      }

     }

let createPerson=(firstname,lastname, mobilenumber)=> {
return new Promise((resolve, reject)=>{
if (users.some(user=> user.mobilenumber===mobilenumber)) {
    reject("The mobile no already exits");
}else{
    obj=new Person(firstname,lastname,mobilenumber);
    users.push(obj);
    resolve(obj.fullName(firstname,lastname,mobilenumber));
    }
  })

}
 let main=()=>{
    createPerson("Lovelesh","Pandey",9372949622)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

    createPerson("Keval","Parikh",6325874159)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

    createPerson("Akash","Sahani",88879879755)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))


createPerson("Siddesh","More",963258417)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

createPerson("Ashwin","GUPTA",963258417)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

createPerson("Sandesh","Kadam",9856564231)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

createPerson("Akshay","Shinde",978456321)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

createPerson("Sakshi","Pandey",985623471)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

createPerson("Sewata","Mishra",9754231865)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

createPerson("Shreya","Mishra",965328741)
    .then((result)=> console.log(result))
    .catch((err)=> console.log(err))

}
main();





</script>